[tool.poetry]
name = "luxeria-led-python"
version = "0.1.0"
description = ""
authors = ["Raphael Nestler <raphael.nestler@renuo.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
